import { AppItem } from '@/types/app';

export const INITIAL_MOCK_APPS: AppItem[] = [
  {
    id: 'app-001',
    name: 'ระบบเผยแพร่ข่าวและประกาศ อบจ.',
    description: 'ศูนย์จัดการและโพสต์ข่าวสาร กิจกรรม งานแถลงข่าว และประกาศทางการของ อบจ.',
    url: 'https://www.facebook.com',
    category: 'งานประชาสัมพันธ์และข่าวสาร',
    icon: 'Megaphone',
    status: 'active',
    order: 1,
    tags: ['ข่าวสาร', 'ประกาศ', 'แถลงข่าว'],
    department: 'ฝ่ายประชาสัมพันธ์',
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'app-002',
    name: 'คลังภาพและวิดีโอกิจกรรม (Media Cloud)',
    description: 'ศูนย์รวมภาพถ่ายความละเอียดสูงและคลิปวิดีโองานกิจกรรม สำหรับสื่อมวลชนและบุคลากร',
    url: 'https://photos.google.com',
    category: 'สื่อ กราฟิก และคลังภาพ',
    icon: 'Camera',
    status: 'active',
    order: 2,
    tags: ['รูปภาพ', 'วิดีโอ', 'คลังภาพ', 'กิจกรรม'],
    department: 'กลุ่มงานผลิตสื่อ',
    createdAt: '2026-01-12T09:30:00.000Z',
  },
  {
    id: 'app-003',
    name: 'ระบบขอรับบริการผลิตสื่อและประชาสัมพันธ์',
    description: 'แบบฟอร์มยื่นคำขอให้ออกแบบกราฟิก ผลิตคลิปวิดีโอ ถ่ายภาพกิจกรรม หรือลงสื่อประชาสัมพันธ์',
    url: 'https://forms.google.com',
    category: 'งานประชาสัมพันธ์และข่าวสาร',
    icon: 'ClipboardList',
    status: 'active',
    order: 3,
    tags: ['ขอใช้บริการ', 'งานออกแบบ', 'ถ่ายภาพ'],
    department: 'ฝ่ายประชาสัมพันธ์',
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'app-004',
    name: 'ศูนย์รวมเทมเพลตและอัตลักษณ์องค์กร (CI & Canva)',
    description: 'โลโก้ ฟอนต์ สีองค์กร และเทมเพลตโปสเตอร์ อินโฟกราฟิกสำเร็จรูปสำหรับหน่วยงานภายใน',
    url: 'https://www.canva.com',
    category: 'สื่อ กราฟิก และคลังภาพ',
    icon: 'Palette',
    status: 'active',
    order: 4,
    tags: ['CI', 'โลโก้', 'เทมเพลต', 'กราฟิก'],
    department: 'กลุ่มงานศิลปกรรม',
    createdAt: '2026-01-20T11:00:00.000Z',
  },
  {
    id: 'app-005',
    name: 'Facebook Page & Meta Business Suite',
    description: 'จัดการเพจ Facebook ทางการ ตอบ Inbox วางแผนโพสต์ และเช็กประสิทธิภาพเพจ',
    url: 'https://business.facebook.com',
    category: 'โซเชียลมีเดียและการตลาด',
    icon: 'Share2',
    status: 'active',
    order: 5,
    tags: ['Facebook', 'โซเชียล', 'Inbox'],
    department: 'ฝ่ายประชาสัมพันธ์',
    createdAt: '2026-01-25T14:00:00.000Z',
  },
  {
    id: 'app-006',
    name: 'TikTok & YouTube Studio อบจ.',
    description: 'ช่องทางการเผยแพร่คลิปสั้น ไฮไลต์กิจกรรม และการถ่ายทอดสด (Live Stream)',
    url: 'https://studio.youtube.com',
    category: 'โซเชียลมีเดียและการตลาด',
    icon: 'Video',
    status: 'active',
    order: 6,
    tags: ['YouTube', 'TikTok', 'Live', 'คลิปสั้น'],
    department: 'กลุ่มงานผลิตสื่อ',
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'app-007',
    name: 'แดชบอร์ดสถิติและการมีส่วนร่วมของประชาชน (PR Insights)',
    description: 'วิเคราะห์ยอด Reach, Engagement, ข่าวที่ได้รับความนิยมสูงสุด และผลสำรวจความคิดเห็น',
    url: 'https://lookerstudio.google.com',
    category: 'สถิติ รายงาน และแบบฟอร์ม',
    icon: 'BarChart3',
    status: 'active',
    order: 7,
    tags: ['สถิติ', 'Analytics', 'รายงาน'],
    department: 'ฝ่ายแผนงานและประเมินผล',
    createdAt: '2026-02-05T13:30:00.000Z',
  },
  {
    id: 'app-008',
    name: 'ระบบสารบรรณอิเล็กทรอนิกส์ (e-Saraban)',
    description: 'ระบบรับ-ส่งหนังสือราชการ บันทึกข้อความ และเอกสารขออนุมัติภายในหน่วยงาน',
    url: 'https://saraban.example.go.th',
    category: 'ระบบงานภายในองค์กร',
    icon: 'FileText',
    status: 'active',
    order: 8,
    tags: ['สารบรรณ', 'หนังสือราชการ', 'งานภายใน'],
    department: 'สำนักปลัด',
    createdAt: '2026-02-10T10:30:00.000Z',
  },
  {
    id: 'app-009',
    name: 'ระบบรับเรื่องร้องเรียนและสายตรงผู้บริหาร',
    description: 'ช่องทางรับเรื่องราวร้องทุกข์ ติดตามสถานะการแก้ไข และประสานงานตอบข้อซักถามประชาชน',
    url: 'https://traffy.example.go.th',
    category: 'เครื่องมือและบริการออนไลน์',
    icon: 'Headphones',
    status: 'active',
    order: 9,
    tags: ['ร้องเรียน', 'สายตรง', 'บริการประชาชน'],
    department: 'ศูนย์บริการประชาชน',
    createdAt: '2026-02-15T15:00:00.000Z',
  },
  {
    id: 'app-010',
    name: 'ระบบสตูดิโอและห้องถ่ายทอดสด (Studio Booking)',
    description: 'ระบบจองห้องสตูดิโอ บันทึกเสียง ถ่ายทอดสด และยืม-คืนอุปกรณ์ถ่ายทำ',
    url: 'https://calendar.google.com',
    category: 'สื่อ กราฟิก และคลังภาพ',
    icon: 'Mic',
    status: 'maintenance',
    order: 10,
    tags: ['จองห้อง', 'สตูดิโอ', 'ยืมอุปกรณ์'],
    department: 'กลุ่มงานเทคนิค',
    createdAt: '2026-02-20T11:20:00.000Z',
  },
];
